### ISSUE TITLE
RuntimeError (EmberCLI Rails require ember-cli NPM package version to be ~> 0.1.5 to work properly

### ISSUE THREAD

**Issue by dougfarre** [rwz/ember-cli-rails#102]
RuntimeError (EmberCLI Rails require ember-cli NPM package version to be
~> 0.1.5 to work properly. From within your EmberCLI directory
please update your package.json accordingly and run:

  $ npm install

):
  ember-cli-rails (0.1.8) lib/ember-cli/app.rb:175:in `check_ember_cli_version!'
  ember-cli-rails (0.1.8) lib/ember-cli/app.rb:162:in `prepare'
  ember-cli-rails (0.1.8) lib/ember-cli/app.rb:32:in `run'
  ember-cli-rails (0.1.8) lib/ember-cli-rails.rb:83:in `block in each_app'
  ember-cli-rails (0.1.8) lib/ember-cli-rails.rb:83:in `each'
  ember-cli-rails (0.1.8) lib/ember-cli-rails.rb:83:in `each_app'
  ember-cli-rails (0.1.8) lib/ember-cli-rails.rb:47:in `run!'
  ember-cli-rails (0.1.8) lib/ember-cli/middleware.rb:23:in `enable_ember_cli'
  ember-cli-rails (0.1.8) lib/ember-cli/middleware.rb:8:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.0) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:8:in `require'
  bin/rails:8:in `<top (required)>'
  spring (1.3.3) lib/spring/client/rails.rb:27:in `load'
  spring (1.3.3) lib/spring/client/rails.rb:27:in `call'
  spring (1.3.3) lib/spring/client/command.rb:7:in `call'
  spring (1.3.3) lib/spring/client.rb:26:in `run'
  spring (1.3.3) bin/spring:48:in `<top (required)>'
  spring (1.3.3) lib/spring/binstub.rb:11:in `load'
  spring (1.3.3) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'

Packages.json
  1 {
  2   "name": "nemo",
  3   "version": "0.0.0",
  4   "description": "Small description for nemo goes here",
  5   "private": true,
  6   "directories": {
  7     "doc": "doc",
  8     "test": "tests"
  9   },
 10   "scripts": {
 11     "start": "ember server",
 12     "build": "ember build",
 13     "test": "ember test"
 14   },
 15   "repository": "",
 16   "engines": {
 17     "node": ">= 0.10.0"
 18   },
 19   "author": "",
 20   "license": "MIT",
 21   "devDependencies": {
 22     "broccoli-asset-rev": "^2.0.0",
 23     "ember-cli": "0.2.0-beta.1",
 24     "ember-cli-app-version": "0.3.1",
 25     "ember-cli-babel": "^4.0.0",
 26     "ember-cli-content-security-policy": "0.3.0",
 27     "ember-cli-dependency-checker": "0.0.7",
 28     "ember-cli-htmlbars": "0.7.4",
 29     "ember-cli-ic-ajax": "0.1.1",
 30     "ember-cli-inject-live-reload": "^1.3.0",
 31     "ember-cli-qunit": "0.3.8",
 32     "ember-cli-rails-addon": "0.0.11",
 33     "ember-cli-uglify": "1.0.1",
 34     "ember-data": "1.0.0-beta.15",
 35     "ember-export-application-global": "^1.0.2",
 36     "express": "^4.8.5",
 37     "glob": "^4.0.5"
 38   }
 39 }

Rails 4.2.0 Ruby 2.2.0

**Comment by rwz** [comment]
It explicitly tells you that "ember-cli NPM package version to be ~> 0.1.5 to work properly"

Your version is "0.2.0-beta.1", which does not conform with "~> 0.1.5" version restriction. Also, there's already an issue for this: https://github.com/rwz/ember-cli-rails/issues/88
