### ISSUE TITLE
Wrong path on Heroku

### ISSUE THREAD

**Issue by sirvine** [rwz/ember-cli-rails#105]
I've got an ember app named 'portfolio' inside my Rails 4 app deployed to Heroku, per the README. When I hit a route that renders `= include_ember_script_tags :portfolio`, I get a 500 error from Rails:

     ActionView::Template::Error (No such file or directory @ rb_sysopen - /app/app/portfolio/package. 
       = include_ember_script_tags :portfolio
       = include_ember_stylesheet_tags :portfolio

My `ember.rb` initializer is:

    EmberCLI.configure do |c|
       c.app :portfolio, path: "app/portfolio"
    end

(I've also tried it without the `path` option.)  In development, the ember app builds and runs just fine.  Any ideas about why production would be looking for Ember assets at `/app/app`?

**Comment by rondale-sc** [comment]
Is your ember application nested inside app folder?  

Could you try if it is flat on the rails root:

```ruby
EmberCLI.configure do |c|
   c.app :portfolio, path: "portfolio"
end
```

**Comment by sirvine** [comment]
That got rid of the redundant `/app/app`, but it's still looking for package.json in the `/app` directory:

      ActionView::Template::Error (No such file or directory @ rb_sysopen - /app/portfolio/package.json)

Also, I can confirm that it's only happening in production, even after moving the Ember app's root.

**Comment by rwz** [comment]
Wild guess: your ember cli app is not actually check in source control. Try cloning your repo into a different folder and check if `portfolio` folder has all the stuff. It probably doesn't.

**Comment by sirvine** [comment]
@rwz Bingo!  I guess I moved an existing Ember app with its own source control into the Rails app. I just needed to remove the Ember app's git tracking and commit the files to the Rails app's source control. I'm sure there's a better way to manage separate source control for Rails/Ember, but I opted for less complexity.

Thanks, and sorry about this not being an ember-cli-rails issue per se.
