### ISSUE TITLE
Should `ember-template-compiler` be required?

### ISSUE THREAD

**Issue by wagenet** [rwz/ember-cli-rails#109]
Right now I'm having to manually import it in my Brocfile. Is this expected?

**Comment by rwz** [comment]
Not enough information. Why do you have to manually import it? What versions of things are you using? How's that relevant to `ember-cli-rails` gem?

**Comment by wagenet** [comment]
This is likely an issue on my end. I think I have conflicting Ember versions. Sorry about that.
