### ISSUE TITLE
does locationType history work?

### ISSUE THREAD

**Issue by danielspaniel** [rwz/ember-cli-rails#111]
In the ember-cli  config/environments.js file there is the setting for locationType:

```
  var ENV = {
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
 },
```

 It is set to auto, and the router then renders plain urls with out prepending '#/' , since the auto setting uses 'history' setting instead of 'hash' ( from Chrome ) , which means rails tries to handle the routes rather than letting ember handle them.   Curious if others are getting things to work with 'history' setting.  I switch to 'hash' and things work fine.

**Comment by thewatts** [comment]
Hey @danielspaniel !

When using the `history` setting, Rails will try to handle those routes unless you explicitly point them to the same controller that is serving your Ember application.

Here's an example from my current project:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  get "/admin", to: "admin#index"
  get "/admin/*path", to: "admin#index" # tell Rails to catch all routes under `admin/`
end
```

**Comment by rwz** [comment]
We've been using similar routes in our apps:

```ruby
get "/app/*path", format: false, to: "ember#index", as: :ember
```

This allows to build ember urls from Rails, like so

```ruby
ember_url("users/#{user.id}/edit") # => "/app/users/123/edit"
```

**Comment by danielspaniel** [comment]
Ok .. thanks @thewatts , @rwz  got it .. you might want to stick that in the docs somewhere .. it's useful info, and it clears up the issue, which is confusing at first.

**Comment by thewatts** [comment]
As a side note, @rwz, did you have to force a trailing slash on your `/app` path for Ember?

In order to set my app's `rootUrl` to `/admin`, I had to configure it to `/admin/`, ex:

```js
// admin/app/router.js
var Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: '/admin/',
});
```

In which case, I had to `301` redirect traffic from `/admin` to `/admin/`.

```ruby
# app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_trailing_slash

  def index
  end

  private

  def ensure_trailing_slash
    unless trailing_slash?
      redirect_to url_for(params.merge(trailing_slash: true)), status: 301
    end
  end

  def trailing_slash?
    request.env['REQUEST_URI'].match(/[^\?]+/).to_s.last == '/'
  end
end
```

**Comment by thesubr00t** [comment]
@thewatts this no longer work for Rails 5, it throws:

> Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.

**Comment by thewatts** [comment]
Hey @thesubr00t honestly - I haven't used this gem in a long long while. You may have better luck with one of the maintainers!

Apologies!
