### ISSUE TITLE
which framework should be making the html doc / ember-cli content-for blocks missing

### ISSUE THREAD

**Issue by nruth** [rwz/ember-cli-rails#113]
I'd like to ask about the top-level html layout (html, head, body, meta) and  which framework generates it.

What HTML template should we provide for the ember app to be inserted into? Just the include_ember_script_tags, or the usual top-level HTML layout and that in the head? It'd help to add this to the readme.

What dom does ember-cli expect? [It provides one](http://www.ember-cli.com/#appindexhtml), and seems that removing things can cause problems: e.g. [handlebars content-for blocks that some ember-cli plugins may be using](https://github.com/ember-cli/ember-cli/issues/2407)?

To be clear, the ember-cli html I was given looks something like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Frontend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/frontend.css">

    {{content-for 'head-footer'}}
  </head>
  <body>
    {{content-for 'body'}}

    <script src="assets/vendor.js"></script>
    <script src="assets/frontend.js"></script>

    {{content-for 'body-footer'}}
  </body>
</html>

```

**Comment by plusplus** [comment]
Hey - also hit this issue - needing guidance on how to replace the content-for handlebars templates in the rails view template for the app. If I find an answer I'll post it here...

**Comment by rwz** [comment]
By default it expects nothing. Just generate a new ember-cli project and run `build` in it and inspect index.html. There's nothing in there.

Here's HAML template in one of our projects:

```haml
%html(lang="en-US")
  %head
    %title ProjectName
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "frontend"
    = csrf_meta_tag
  %body
```

**Comment by rwz** [comment]
You need to make sure you include relevant css and javascripts. Everything else is optional. By default Ember attaches itself to the body element.

**Comment by plusplus** [comment]
Thanks for reply - I appreciate it... In the end it was me not configuring base url for the ember app properly and hunting down the problem in the wrong place (the index file).

**Comment by nruth** [comment]
This isn't accurate. See the link I gave.
http://www.ember-cli.com/#appindexhtml

> In addition to this, app/index.html includes multiple hooks - {{content-for 'head'}} and {{content-for > 'body'}} - that can be used by Add-ons to inject content into your application’s head or body. These hooks > need to be left in place for your application to function properly, but they can be safely ignored unless > you are working directly with a particular add-on.

and also the recent index template:
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/index.html

**Comment by nruth** [comment]
Sorry if that comes over rude. What I mean is, isn't this about integrating with ember-cli, rather than ember? Shouldn't it support these ember-cli plugin hooks? They say it's required, not optional.

I'm not actually using anything like that now so can't provide a use-case, but it seems like it needs addressing in the readme.

**Comment by rondale-sc** [comment]
@nruth, I agree that supporting these addon hooks is important.  I'm going to look into how `ember-cli-rails-addon` can help pass this through to the appropriate section in rails land (since we don't render the EmberCLI index.html from the rails app).

**Comment by nruth** [comment]
I took a look into it more to try to help (I'm an ember-cli/node beginner).

As far as I can tell:

- When rendering the index, cli uses broccoli-config-replace to process some placeholders, so ember-cli-rails doesn't do this part and leaves the {{placeholders}} in the template. [EmberApp.prototype.index](https://github.com/ember-cli/ember-cli/blob/b0f0aed8d45af589da9d97069c92bd73313a9119/lib/broccoli/ember-app.js#L380)
- [EmberApp.prototype._configReplacePatterns](https://github.com/ember-cli/ember-cli/blob/b0f0aed8d45af589da9d97069c92bd73313a9119/lib/broccoli/ember-app.js#L433) defines the supported placeholders
- content-for placeholders are handled by [EmberApp.prototype.contentFor](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#contentfor), which seems to scan the rendered template and all addons, building up the string to put into the content block.

I see two approaches: inserting rails stuff into ember-cli's template, or inserting ember-cli stuff into rails.

Pushing rails stuff into ember could be done by wrapping the things we want to keep from rails (asset pipeline links, csrf token) in rails content_for blocks, and somehow forwarding those to a contentFor function in ember-cli-rails-addon. They give an example of an [analytics plugin inserting something](https://github.com/pgrippi/ember-cli-google-analytics/blob/v1.3.1/index.js#L79). I don't think anyone will like this because it means giving up rails templates.

Pulling the ember-cli content-for text out and putting it into rails seems harder. Maybe [EmberApp.prototype.index](https://github.com/ember-cli/ember-cli/blob/b0f0aed8d45af589da9d97069c92bd73313a9119/lib/broccoli/ember-app.js#L380) or something lower down can be tweaked/extended to render json into a tempfile that ember-rails-cli reads and writes into rails's content_for.

**Comment by rondale-sc** [comment]
I think this is probably the right path.

> Pulling the ember-cli content-for text out and putting it into rails seems harder. Maybe EmberApp.prototype.index or something lower down can be tweaked/extended to render json into a tempfile that ember-rails-cli reads and writes into rails's content_for.

I'm going to talk this over with @rwjblue (he seems to have an idea of what might need to be done) and plan out a road map.
