### ISSUE TITLE
Emblem and CoffeeScript

### ISSUE THREAD

**Issue by salex** [rwz/ember-cli-rails#118]
This is out of my league at this point in that I've only looked at Ember the last couple days and maybe asked to help with something I have little or no experience with.

My first impression was with handlebars, just another concept like erb. I NEVER WANT TO WRITE HTML OR ANYTHING ELSE THAT HAS CLOSING TAGS (other than END). I don't care how good an editor is, I can tab better than missing closing tags.  I found emblem and CoffeeScript plugins for ember, but they didn't seem to work with ember-cli-rails.

Found a post that touts emblem and CoffeeScript and how to install it (http://blogs.visoftinc.com/2014/07/24/setting-up-ember-cli-with-emblem-and-coffeescript/)  with something call Broccoli but it does not seem to work with ember-cli-rail.  Looks like it it stuck with a version on handlebars.

This may be a moot point in that I think want I may be asked to help is using a pure CLI version with a Rails API application, but I'm just curious what is the right approach.  Sorry for the shooting, but I've wasted too much time in my life look for a missing closing html tag or a misplaced } or ) or missing ;

**Comment by rwz** [comment]
We're using CoffeeScript and it works alright for us. For templates you can try something like http://www.hbars.io/

**Comment by rondale-sc** [comment]
@salex I concur, we've used [hbars](https://github.com/code0100fun/ember-cli-hbars) to great success on several side projects.  I think it is production ready, and @code0100fun is pretty responsive to issues.   :cheers:

**Comment by batamire** [comment]
+1 for @salex, slim is better than haml ;)

**Comment by PatrickKing** [comment]
For future readers, the tutorial linked to in the first comment is out of date. As of this writing you can get coffeescript working in ember-cli-rails the ember-cli-coffeescript package. In your ember app's directory:
`ember install ember-cli-coffeescript`
Similarly, for emblem:
`ember install ember-cli-emblem`
And yes, +1 for indentation scoped languages! The river of `end`s at the end of every file is one of Ruby's few blemishes.
