### ISSUE TITLE
Unable to compile assets after installing the Ember-CLI-Rails

### ISSUE THREAD

**Issue by alexstophel** [rwz/ember-cli-rails#120]
Love the idea of this gem!

I've been messing around with it for a couple of hours and I'm unable to get the assets to compile after following the instructions in the README. I've got an Ember-CLI app called frontend that lives in the root folder of the rails app.

I'm getting the following errors when I run the the server and attempt to visit the page:

```
ActionController::RoutingError (No route matches [GET] "/stylesheets/frontend/frontend.css"):
```

In the Chrome console, I also get 404's for the following files:

```
http://localhost:3000/javascripts/frontend/vendor.js 
http://localhost:3000/stylesheets/frontend/vendor.css 
http://localhost:3000/javascripts/frontend/frontend.js 
```

In the terminal where the server is running, I am getting the warning message, ```Seems like Ember frontend application takes more than 5 seconds to compile. ```

When I try to run ```rake assets:precompile``` I get the following error:

```
NoMethodError: undefined method `directory?' for nil:NilClass
```

I'm sure this is user error and I've messed up somewhere--I'm just not able to locate the problem. Do you have any suggestions?

**Comment by rondale-sc** [comment]
Could you post your ember initializer here it might be an issue with configuration.  Also, could you `cd` into your ember application and run `ember -v` and send me the output of that as well.  Thanks!

**Comment by jzumaran** [comment]
@rondale-sc Hi there, I'm having the same exact issue, my ember initializer is:

    EmberCLI.configure do |c|
      c.app :admin, path: Rails.root.join('admin').to_s
    end

And when i do ember -v I get the following output:

    The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/jzumaran/Desarrollo/Gitz Templates/rails-mongo-ember-admin/admin/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
    Future versions of Ember CLI will not support v0.10.35. Please update to Node 0.12 or io.js.
    version: 0.2.0
    Could not find watchman, falling back to NodeWatcher for file system events
    node: 0.10.35
    npm: 2.7.0

Thank you.

**Comment by alexstophel** [comment]
Absolutely. Thanks for looking into this for me.
```
EmberCLI.configure do |c|
  c.app :frontend
end
```

```ember -v``` in frontend folder:
```
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/alexstophel/Development/Bloc Full Stack/CodeItForward/frontend/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Future versions of Ember CLI will not support v0.10.37. Please update to Node 0.12 or io.js.
version: 0.2.0
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.37
npm: 2.7.0
```

**Comment by coladarci** [comment]
@alexstophel  - did you happen to make any progress? I'm having the same symptoms as you are and while ember-cli is playing quite nice, the rails side of things isn't. Most of the time, the symptoms are exactly as you describe, the strange part is that 10% of the time, or so, it does find the .js and .css files and about 20% of the time it stops recognizing the app and just says `EmberCLI app "frontend" has failed to build`

Like you, I assume I'm doing something wrong, but have little to go off of. Anyone have any advice?

**Comment by alexstophel** [comment]
@coladarci,

Unfortunately, I've still not been able to find a solution. Sorry! I'm hoping someone will respond here soon.

**Comment by coladarci** [comment]
I'm battling this as we speak - 

The 404s go away, for the most part, when I realized that I probably shouldn't be running `ember server` inside my ember app folder. 

That said, I've never seen a more mysterious gem than this one.... 

As it stands now, any file I touch results in my rails app saying that it can't build the ember app. To fix it, I run `ember build`. 70% of the time the page will now load, but the other 30% it throws those 404's from before and I have to restart my server.

**Comment by Leooo** [comment]
Same problem here, when I first start my rails server I get a "not found" error looking for a file in "javascripts/frontend/vendor". When I reload the page most of the times it's right, but then guard doesnt always rebuild ember frontend.js and I have to type "ember build" often to make frontend.js resfresh after changes.

EmberCLI.configure do |c|
     c.app :frontend, path: Rails.root.join('frontend').to_s
en `

**Comment by rondale-sc** [comment]
@coladarci @Leooo Could this be rearing its head again? 

 https://github.com/ember-cli/ember-cli/issues/3413

Possibly with a different package.  I had a similar problem not too long ago but I just pinned rimraf and it went away.  Either way if the problem is happening when you ember build this issue likely belongs on ember-cli's issue tracker.  Let me know what you find!  :))

**Comment by coladarci** [comment]
hey @rondale-sc - can't speak for @Leooo, but as per the steps to reproduce, this **never** happens with `ember build`; that's the only command that is behaving at the moment.

**Comment by purezen** [comment]
Hi guys, I am having the same issue as well.

**Comment by rwz** [comment]
Can anybody provide a repo recreating the problem?

**Comment by purezen** [comment]
@rwz I am facing the issue running this: https://github.com/hummingbird-me/hummingbird.

**Comment by rwz** [comment]
@purezen cool. I'll probably look into that later today.

**Comment by purezen** [comment]
@rwz :+1:

**Comment by rwz** [comment]
@purezen hummingbird compiled ok for me. All files are present and everything seems to be working fine.

**Comment by rwz** [comment]
@alexstophel you have to increase your build timeout like the warning suggests. The default value waits for 5 seconds for the initial build and releases the lock if it takes longer. This results in 404 for the files that are not done compiling yet.

I assume you're getting `NoMethodError: undefined method `directory?' for nil:NilClass` for the same reason.

**Comment by alexstophel** [comment]
@rwz, I tried that. It still doesn't fix the errors. :(

**Comment by Leooo** [comment]
In my case increasing the timeout solved the issue. Should have tried before asking obviously, but there are many different things to apprehend when installing ember-cli-rails. For example, it was not clear (and still is not) when the frontend.js / vendors.js are supposed to be built during development. Thanks anyway @rwz.

**Comment by Leooo** [comment]
@alexstophel, looking at your watchman message I had the same at the beginning and then managed to properly install watchman by reading the corresponding threads on SO, maybe this would solve your issue (??)

**Comment by rwz** [comment]
@alexstophel can you submit a repo reproducing the problem?

**Comment by purezen** [comment]
@rwz My Chrome window shows this, though

![screen shot 2015-04-01 at 1 24 36 pm](https://cloud.githubusercontent.com/assets/3036093/6936700/914e6c14-d872-11e4-9805-5b6e239c6025.png)

**Comment by mehulkar** [comment]
Did people figure this one out? I'm running into the 404 issue. I'm not sure why the `include_ember_script_tags` helper is looking for the js file in that place. Or should I be building the assets before trying to serve them through rails?

**Comment by joshpfosi** [comment]
I am still experiencing this issue.

**Comment by constantm** [comment]
Same issue here.

**Comment by mehulkar** [comment]
I believe I solved this problem by setting the `build_timeout` to a higher value. it's `5` by default. I think 10 worked for me.

**Comment by joshpfosi** [comment]
I have tried high values for the timeout and it did not resolve my issue :(

**Comment by kgish** [comment]
This is a big problem for me, as I need to deploy my ember+rails app and cannot find a proper way to do this.

Cannot imagine that this hasn't been thought up of already a long time ago, isn't that the magic of creating an ember app anyway, together with a fancy back-end like Rails?

What are people doing nowadays in order to deploy an ember-client and rails app on the same server?

(Ember.js + Rails API + Bootstrap + Capistrano + Passenger + Apache)

I've looked around endlessly and there just doesn't seem to be a standard solution out there that works, or not?

**Comment by constantm** [comment]
@kgish Most straightforward would be to develop your Ember app separately from your backend. You can then serve your Ember files as static assets on production, which just interfaces with your API.

**Comment by kgish** [comment]
@constantm Is there some guidelines or user guide for doing this using Ember, Bootstrap, Rails, Passenger, Apache and Capistrano? I would have to build the ember stuff and deploy it to the static assets directory or something like that?

**Comment by mehulkar** [comment]
I typically run a cap task to place the compiled assets `/www` or whatever.

Nginx is configured to send / requests to that dist dir and send /api requests to the rails server. (Forces us to use hash location, but not a big deal)

```conf
server {
  listen 80;
  location / {
    root /www/;
  }
  location /api {
    proxy_pass http://localhost:3000;
  }
}
```

**Comment by kgish** [comment]
Since `ember-cli-rails` seems to be a bit of a hassle now, I see nothing wrong with your approach.

In my case I am using apache instead of nginx, so something similar would work.

@mehulkar: Could you share your cap tasks with me?

**Comment by mehulkar** [comment]
This works pretty well

```ruby
namespace :frontend do
  task :build_all do
    on roles(:app) do
      # delete old dep and old tmp build
      execute "rm -rf #{release_path}/bower_components || true"
      execute "rm -rf #{release_path}/node_modules || true"
      execute "rm -rf #{release_path}/new-dist || true" # just in case there was a bad deploy before

      # install deps
      execute "cd #{release_path} && npm install"
      execute "cd #{release_path} && bower install"

      # build
      execute "cd #{release_path} && ember build --output-path=#{release_path}/new-dist --environment=production"

      # replace current dist with new dist
      execute "mkdir -p #{release_path}/dist" # In case it doesn't exist already (first time deploy)
      execute "mv #{release_path}/dist #{release_path}/old-dist"
      execute "mv #{release_path}/new-dist #{release_path}/dist"
      execute "rm -rf #{release_path}/old-dist || true"
    end
  end
end
```

**Comment by simsalabim** [comment]
I'm experiencing similar issue: application I'm working on doesn't load due to inability to find `/assets/vendor.js` at boot. The route works fine in isolation; the build doesn't time out (and even increasing timeout doesn't help).

I'm following README setup and use `mount_ember_app :frontend, to: "/"` along with overridden view `<%= render_ember_app :frontend`.

What makes it worse, is that the application loads just fine every 5-6th time. The issue happens sporadically in development, and the same goes to production env.

Any advice on how it can be solved is highly appreciated.

**Comment by simsalabim** [comment]
Maybe it makes sense to reopen the issue to attract active OSS contributors attention?

**Comment by JMazzy** [comment]
having the same issue @simsalabim, using all the defaults and following the instructions exactly

**Comment by JMazzy** [comment]
there are no build errors or anything, just the 404s

**Comment by seanpdoyle** [comment]
@simsalabim @JMazzy sorry that you're having trouble.

We've recently [just added an issues template](https://github.com/thoughtbot/ember-cli-rails/commit/91e368c9bf107dc56b6d1be370afa3c051cb8df4) to this repo.

Could either (or both) of you open an issue describing your troubles while following along with the template?
