### ISSUE TITLE
heroku deploy cannot find bower

### ISSUE THREAD

**Issue by langalex** [rwz/ember-cli-rails#130]
the line `"postinstall": "../../node_modules/bower/bin/bower install"` mentioned in the readme doesn't work for me, it can't find bower. where is this directory supposed to come from?

**Comment by langalex** [comment]
btw it works when I change it to just `bower install` without any directories.

**Comment by rwz** [comment]
Thanks for bringing this up.

**Comment by rupurt** [comment]
Howdy,

I'm running into a similar problem trying to get our app deployed on Heroku.

Ember CLI [recommends installing bower globally](http://www.ember-cli.com/user-guide/#bower) and it seems like bower doesn't get installed as part of the default Heroku node buildpack. I've tried setting `NPM_CONFIG_PRODUCTION=false` as recommended in the [docs](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process), but that doesn't make a difference.

Do I need to install bower globally in the `preinstall` or `postinstall` hook of the root `package.json`?

We're using:
- Node 4.1.0
- NPM 2.14.3
- Ember CLI 1.13.8
