### ISSUE TITLE
heroku deploy doc rewordings

### ISSUE THREAD

**Issue by nruth** [rwz/ember-cli-rails#134]
A few things that tripped me up:

> Next, check in .buildpacks file to specify which buildpacks to use:

The file doesn't exist after installing the Heroku addon. Is that supposed to happen, or did heroku cli not work properly? Should the instructions instead say create a .buildpacks file in the root with the given values?

> Make sure you have bower in the dependencies list of your app.

Is this a Rails, ember-cli, or Heroku setting?

It'd also be reassuring to have a note explaining whether and how the app gets precompiled, as we don't tell anything where to find our ember-cli app during the Heroku setup steps.

**Comment by jamescgibson** [comment]
Dunno about your second question, but for the first, .buildpacks isn't included by default, as the standard deployment process only uses one buildpack which is inferred from the project files.

**Comment by nruth** [comment]
For 2: need to add to ember-cli project, e.g. `ember install:npm bower`, since those following the ember-cli guide will have a global install of bower instead of a project dependency.

For the last bit it looks like the asset pipeline is handling it, which is great but a bit magic.

I'll try to clarify it and make a PR.
