### ISSUE TITLE
undefined method `include_ember_script_tags' 

### ISSUE THREAD

**Issue by jesenko** [rwz/ember-cli-rails#147]
After upgrading to latest version of ember-cli-rails (0.3.1), ember-cli helpers are not available in views. I had to manually add `helper EmberCLI::EmberRailsHelper` to controller to include them. Probably related to https://github.com/rwz/ember-cli-rails/commit/96f4d91f27bcf2e8b2a0f78ccc6e4229abfa2b7d.

Either documentation should be updated to manual inclusion of helpers or helpers should be automatically included.

Rails version: 4.1

**Comment by rwz** [comment]
That's weird because it works for me. The engine exposes all its helpers be default.

**Comment by rwz** [comment]
Could you provide a test app exposing the issue?

**Comment by jesenko** [comment]
I traced it back to this entry in Rails config:

    config.action_controller.include_all_helpers = false

Apparently engine does not expose its helpers if this is set...

**Comment by jesenko** [comment]
I have created related PR #148
