### ISSUE TITLE
BuildError on every change after upgrading to Ember-cli 0.2.3

### ISSUE THREAD

**Issue by ryanlntn** [rwz/ember-cli-rails#150]
Perhaps this is watchman related. I'm getting a lot of recrawled warnings. Has anybody seen similar issues?

**Comment by rondale-sc** [comment]
@ryanlntn I haven't experienced this on my project.  However, when this has happened in the past it was a node issue with the rimraf version.  I'd suggest looking at this issue: https://github.com/ember-cli/ember-cli/issues/3413  Might send you in the right direction.

**Comment by ryanlntn** [comment]
Thanks for the suggestion @rondale-sc. I'll close for now as it does look to be a node/ember issue.
