### ISSUE TITLE
When I use capistrano I must use `deploy:compile_assets`?

### ISSUE THREAD

**Issue by JeskTop** [rwz/ember-cli-rails#160]
I want to cap my application in my server by capistrano. If I user `cap production deploy`, I will get this message:
```
DEBUG [6298731b] 	Run `bower install` to install missing dependencies.
```
And I check the `public/assets/frontend`, I can not find `vendor.js` and `frontend.js`. So I use `cap production deploy:compile_assets`, ember-cli can work:
```
DEBUG [4a403385] 	version: 0.2.3
DEBUG [4a403385] 	Building
DEBUG [4a403385] 	Building.
DEBUG [4a403385] 	Building..
DEBUG [4a403385] 	Building...
DEBUG [4a403385] 	Building
DEBUG [4a403385] 	Building.
```
After this will create `vendor.js` and `frontend.js` file in `public/assets/frontend` and the application can work.

So I very confusion, this is my problem or if I use `ember-cli-rails` I must use `deploy:compile_assets`.

If my problem, can you tell me what is problem with my application. My application:
```
ember-cli-rails (0.3.1)
"ember": "1.11.3"
"ember-cli": "0.2.3"
```
 Thx.

**Comment by rwz** [comment]
Make sure you capistrano script actually runs `assets:precompile` on the server. If it does, make sure it work alright and not blows up for some weird reason. If you don't want to run it on the server on each deploy, make sure you run it before deployment locally and that all necessary files are included.
