### ISSUE TITLE
EmberCLI Rails not seeing ember-cli-rails-addon when deploying to Heroku

### ISSUE THREAD

**Issue by ryanlntn** [rwz/ember-cli-rails#166]
I have this working on a staging server but for some reason when I try to push the same app to production I get:

`RuntimeError: EmberCLI Rails requires your Ember app to have an addon. From within your EmberCLI directory please run: $ npm install --save-dev ember-cli-rails-addon@0.0.11 in you Ember application root`

But it is in `package.json`:

```json
"devDependencies": {
  "ember-cli-rails-addon": "0.0.11",
}
```

Any idea what might be going on here?

**Comment by ryanlntn** [comment]
Nevermind. It looks like I was using the wrong buildpack.

**Comment by arinhouck** [comment]
Can you specify what you did to fix this problem? Wrong version? Notes on changes?

**Comment by ryanlntn** [comment]
I forgot to configure production to use the multi build pack. Running `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi` on production resolved the issue for me.

**Comment by austinarchibald** [comment]
Having this same problem. Have confirmed the addon in `package.json`. I tried running `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi ` in my terminal as you said, and now it says:

```bash
remote: -----> Fetching custom git buildpack... done
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
```

Any ideas? Thanks.
