### ISSUE TITLE
Make original ember tests available through rails routes

### ISSUE THREAD

**Issue by rwz** [rwz/ember-cli-rails#18]
Make http://localhost:4200/tests/* available through rails somehow.

//cc @mwoods79

**Comment by MichaelVdheeren** [comment]
+1 What's the status of this?

**Comment by rwz** [comment]
@MichaelVdheeren nobody's working in this yet. You can take a shot if you feel like it.

**Comment by seanpdoyle** [comment]
@rwz where do we manage where the builds go? What would it take to get this done?
