### ISSUE TITLE
update EMBER_CLI_VERSION to use with ember-cli@1.13.0

### ISSUE THREAD

**Issue by webark** [rwz/ember-cli-rails#182]
Need up update at least this flag in order to use the updated ember-cli.

Changed the ember check and appears everything is working fine.

**Comment by franzliedke** [comment]
:+1:

**Comment by mxaly** [comment]
:+1:

**Comment by JeskTop** [comment]
:+1:

**Comment by rzane** [comment]
Definitely needs a PR. In the meantime, I threw this into an initializer:

```ruby
EmberCLI::App::EMBER_CLI_VERSION = ['~> 1.0']
```

**Comment by webark** [comment]
oops.. course you can override it... Duh.. ok cool. thanks @rzane !!

**Comment by skylar** [comment]
PR submitted:  #183

thanks @webark!

**Comment by rwz** [comment]
Fixed and released 0.3.3
