### ISSUE TITLE
Updating ember-data.js and ember.js libraries

### ISSUE THREAD

**Issue by begin29** [rwz/ember-cli-rails#185]
How can I manually update ember-data and ember.js files?

Ember libraries changes so fast that some documented options don`t work. 

E.g. ember-data within gem is 1.0.0-beta.17, but current version is 1.13.5.

**Comment by rwz** [comment]
The gem does not ship ember-data or ember-cli npm packages. It's designed to be an integration between ember-cli and rails, nothing more.

**Comment by begin29** [comment]
Thanks for reply. I'll try to update this manualy.
24 лип. 2015 19:22 "Pavel Pravosud" <notifications@github.com> пише:

**Comment by supairish** [comment]
@begin29 Update the versions in your bower.json.  Then bower install.

**Comment by begin29** [comment]
Yeah! Thanks a lot
24 лип. 2015 20:20 "Chris Irish" <notifications@github.com> пише:

**Comment by begin29** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkdpYTFPdzVIRWVhWVp3NnlleUx5RnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQzODZhNzVmZjhkOTFlNGZmYTkwOWNkN2EzZTYwODdjOTJjNTk4ODg1MmMzYTU5MmNmMDAwMDAwMDExMWNhMzVkYzkyYTE2OWNlMDVjODE1YjhAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyJ9fSwidXNlcklkIjotMX0.VH-KKN7KPA28vxJOM1GO4qAY3bPVc1Pxmrnqjnwi7Bw> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkdpYTFPdzVIRWVhWVp3NnlleUx5RnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQzODZhNzVmZjhkOTFlNGZmYTkwOWNkN2EzZTYwODdjOTJjNTk4ODg1MmMzYTU5MmNmMDAwMDAwMDExMWNhMzVkYzkyYTE2OWNlMDVjODE1YjhAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyJ9fSwidXNlcklkIjotMX0.VH-KKN7KPA28vxJOM1GO4qAY3bPVc1Pxmrnqjnwi7Bw> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5HaWExT3c1SEVlYVladzZ5ZXlMeUZ3IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA0Mzg2YTc1ZmY4ZDkxZTRmZmE5MDljZDdhM2U2MDg3YzkyYzU5ODg4NTJjM2E1OTJjZjAwMDAwMDAxMTFjYTM1ZGM5MmExNjljZTA1YzgxNWI4QHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLkdpYTFPdzVIRWVhWVp3NnlleUx5RncifX0sInVzZXJJZCI6LTF9.9Z4_aWl8HjgQhwAh6ML3Ba_mQbLKbuJRBt6tawb2pZo>


Vadym Motsukh thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49YWNlNmE2OGQ1MTBiOGIzNjcyZDM3ZmI0ZmM0OTMyYmQmZW1haWw9cmVwbHkrMDA0Mzg2YTc1ZmY4ZDkxZTRmZmE5MDljZDdhM2U2MDg3YzkyYzU5ODg4NTJjM2E1OTJjZjAwMDAwMDAxMTFjYTM1ZGM5MmExNjljZTA1YzgxNWI4QHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1yd3ovZW1iZXItY2xpLXJhaWxzP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkdpYTFPdzVIRWVhWVp3NnlleUx5RnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQzODZhNzVmZjhkOTFlNGZmYTkwOWNkN2EzZTYwODdjOTJjNTk4ODg1MmMzYTU5MmNmMDAwMDAwMDExMWNhMzVkYzkyYTE2OWNlMDVjODE1YjhAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyJ9fSwidXNlcklkIjotMX0.SMUexej44mOG5-XTCHvFHRWQ5tZGWmBHCQLrtJjN6gA>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5HaWExT3c1SEVlYVladzZ5ZXlMeUZ3JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQzODZhNzVmZjhkOTFlNGZmYTkwOWNkN2EzZTYwODdjOTJjNTk4ODg1MmMzYTU5MmNmMDAwMDAwMDExMWNhMzVkYzkyYTE2OWNlMDVjODE1YjhAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyJ9fSwidXNlcklkIjotMX0.gZR0jn0wPDhB7QCG2rihTfzlmMlbApYIjiXw0uMiV3I> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDM4NmE3NWZmOGQ5MWU0ZmZhOTA5Y2Q3YTNlNjA4N2M5MmM1OTg4ODUyYzNhNTkyY2YwMDAwMDAwMTExY2EzNWRjOTJhMTY5Y2UwNWM4MTViOEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5HaWExT3c1SEVlYVladzZ5ZXlMeUZ3In19LCJ1c2VySWQiOi0xfQ.5Hu3NCe9VAwnM6USFGoE4nCavOdCmvTpWba_QwCUYdc>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDM4NmE3NWZmOGQ5MWU0ZmZhOTA5Y2Q3YTNlNjA4N2M5MmM1OTg4ODUyYzNhNTkyY2YwMDAwMDAwMTExY2EzNWRjOTJhMTY5Y2UwNWM4MTViOEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5HaWExT3c1SEVlYVladzZ5ZXlMeUZ3In19LCJ1c2VySWQiOi0xfQ.NMokSpipmk6dWE-3Dy_EFzyiXor6aDSz0MUsq1Ckfvk> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS83cU1xYV9YT3J5bUpuMldCNFd1eDJxSklQVURBaDhDaEtvQ0c4OGE3ZjJQd09BTkxIQkM1T3Jhc2dEWF91YjlQMi1FNU1feEZNYzh1VW9pajNJZVZQdy5zVTlFSDZ6bDFLalg3S2thUnFVUHNBLmRMaWE1aG9YWnJUVnpXLTlUM2o3eTNhalNiUEVJSnBBTFNUTnp0VXlaTTN0OW0tY2NaUGxnb3ZUR0h0VGhnRW5LQlJYeGhkbHlxWVg1ekxiNjVzYXVKYTVJQUZ5UGxTU2VWUnB2SUxxOVJNREVIU1VBX1g0dlhvMXJscUVKdm4wUmxOTHlQT0g1MTZFc2J4LVZYYVZRY1NlUmw1SGp5VGhlU0tfblAwQjZzUnFETmd1WkdKSTVlZm9UVXpPQ0t6U1NzTWNBa0k1WTRtQkl4bjVvLTdJSWwxXzVSNUZnRnVMNzl4UmZVNXdQWkxsNDQ1c2hOMU1VRTZtSVFYRGVlazRyV2xmdnRvYlFLcDAxR3c1OEUxTkF5N0lpV0lPTktYWmVGaFduMGJfYzhZP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkdpYTFPdzVIRWVhWVp3NnlleUx5RnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQzODZhNzVmZjhkOTFlNGZmYTkwOWNkN2EzZTYwODdjOTJjNTk4ODg1MmMzYTU5MmNmMDAwMDAwMDExMWNhMzVkYzkyYTE2OWNlMDVjODE1YjhAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uR2lhMU93NUhFZWFZWnc2eWV5THlGdyJ9fSwidXNlcklkIjotMX0.W4zoSbUMu7RZ2muCk2VDB5ORHftX5I57PjhV8xwfr-s>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
