### ISSUE TITLE
No route matches when I go an ember router

### ISSUE THREAD

**Issue by GCorbel** [rwz/ember-cli-rails#201]
Hello,

I'm new with ember and I'm trying ember-cli-rails. I configured the initializer like this : 

    EmberCLI.configure do |c|
      c.app :frontend, path: '../frontend'
      c.build_timeout = 30
    end

And I copied/pasted codes on the README to my application/index.html.erb and application_controller.rb files. When I go at `http://localhost:3000` it works. I added a route and a link lie this : 

    <h2 id="title">Welcome to Ember.js</h2>

    {{#link-to 'users'}}Test{{/link-to}}
    {{outlet}}

When I click on the link, the current paths is `http://localhost:3000/users` and it works. The problem is, when I reload, I have a `No route matches [GET] "/users"` and all routes I see on the error page comes from Rails.

Should the ember's routes be mounted? Is there a way to fix that issue? What's the best practice?

Thanks!

**Comment by GCorbel** [comment]
I had an answer here : http://stackoverflow.com/questions/32168466/ember-cli-rails-no-route-match-for-embers-paths. I had to add : 

    get '/:all', to: "application#index"

to my routes.

It should be in the Readme!

**Comment by gnapse** [comment]
It really should be in the README!

**Comment by benoittgt** [comment]
Thanks to add it to read me. I'm having the same problem but on a little bit more complex app. 

http://stackoverflow.com/questions/32712198/ember-cli-rails-routing-close-to-a-classic-rails-app

**Comment by GCorbel** [comment]
It should be `get '/*all', to: "application#index"` to include all pathes.
