### ISSUE TITLE
The api is not called on acceptance tests

### ISSUE THREAD

**Issue by GCorbel** [rwz/ember-cli-rails#202]
Hello,

I have this simple test with capybara : 

    require 'rails_helper'

    feature 'Users' do
      scenario 'Can show all users', js: true do
        create(:user, nickname: 'Nickname')
        visit '/users'
        click_on 'Users'
        expect(page).to have_content('Nickname')
      end
    end

This route : 

    export default Ember.Route.extend
      model: (params) ->
        @store.findAll('user')

This action : 

    module Api
      module V1
        class UsersController < Clearance::UsersController

          def index
            render json: User.all, include: ['trails']
          end
       end
     end

And this adapter : 

    import $ from 'jquery'

    export default DS.JSONAPIAdapter.extend
      namespace: 'api/v1'
      headers:
        "X-CSRF-Token": $('meta[name="csrf-token"]').attr('content')

It works in development but in test the api is never called.

Is there something to do?

Thanks!

**Comment by supairish** [comment]
I'd put a sleep 10 after your
```
click_on 'Users'
```

and a byebug statement on the first line of your index action, then run the test.  You'll know real quick whether the issue is Capybara not waiting for the ajax call or that you're really not hitting that index action.

**Comment by GCorbel** [comment]
I was wrong. The api is called because the breakpoint is triggered in the controller. `User.all` returns an empty array on the controller and 1 record on the spec. I already had this problem and I will check if I can find something.

**Comment by GCorbel** [comment]
Solved, it was because of this line `  config.use_transactional_fixtures = false`. I have to use DatabaseCleaner now... Thanks!
