### ISSUE TITLE
Detect broken build state

### ISSUE THREAD

**Issue by rwz** [rwz/ember-cli-rails#23]
Sometimes EmberCLI fails to build assets due to syntax error. Rails does not provide any sort of feedback and continues to serve an old pre-fail version of assets. All that results in the situation where developer refreshes the page several times not realizing that the changes he just made are not included into the resulting assets.

It'd be nice to make EmberCLI::Rails gem to have an ability to detect this state and display an error view similar to the one you see when Assets Pipeline fails to build an asset.

Is there a way to do that without parsing EmberCLI build process output? Maybe there could be a hidden file containing last build error, so we could check for its existence to detect a broken build state?

//cc @rwjblue

**Comment by rwz** [comment]
We need to make this work. If only there were like 30 hours in a day and less other awesome things to procrastinate on.

**Comment by rondale-sc** [comment]
@rwz 

https://github.com/rondale-sc/ember-cli-rails-addon/tree/v0.0.9

**Comment by rondale-sc** [comment]
Yay!
