### ISSUE TITLE
Start apps lazily.

### ISSUE THREAD

**Issue by rwjblue** [rwz/ember-cli-rails#26]
If I have multiple ember-cli apps mounted at various routes (I am working on an app with 6), starting them all for each `rails s` can take quite a bit of time.

If each ember app takes 3-5 seconds to build, and I have 10 apps running it will take 30-50 seconds to boot rails server (we do a sync build AND an async watch for all apps on boot).  This is regardless of hitting any of the ember routes (meaning, if I just want to hit a standard rails route I have to wait the total time).

Dissecting this a bit:

- [x] ~~Do not [compile](https://github.com/rwz/ember-cli-rails/blob/8ae7c3605840a4290a7b6dd1c3e2ff01a45f86ee/lib/ember-cli-rails.rb#L35) && [run](https://github.com/rwz/ember-cli-rails/blob/8ae7c3605840a4290a7b6dd1c3e2ff01a45f86ee/lib/ember-cli-rails.rb#L36) the EmberCLI app.  Only one should be needed, it seems that a sync build is required to ensure content exists in `dist/`. I believe that the locking middleware in https://github.com/rwz/ember-cli-rails/pull/25 fixes this for us.~~  Fixed in https://github.com/rwz/ember-cli-rails/pull/25.
- [ ] Only start apps when their routes are visited. Removes the need for [SKIP_EMBER](https://github.com/rwz/ember-cli-rails/commit/32d83e42b33a8a113ecac22d38afe0bc85ecb688) environment variable.

DISCLAIMER: 

I could be missing something obvious that makes these points untrue.

**Comment by rwz** [comment]
Alright, that didn't work out as expected. Closing this issue for now. Will reopen/recreate if a better way to achieve the same effect is found.

**Comment by rondale-sc** [comment]
@rwz Understatement.  lol.  Good learning experience though.
