### ISSUE TITLE
deploying to heroku: ember-cli executable not found

### ISSUE THREAD

**Issue by samselikoff** [rwz/ember-cli-rails#33]
Any thoughts on this? Is it possible to have the server install `ember-cli` via `ember-cli-rails`?

```sh
remote:        ember-cli executable could not be found
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/configuration.rb:22:in `block in ember_path'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/configuration.rb:21:in `tap'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/configuration.rb:21:in `ember_path'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/app.rb:72:in `ember_path'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/app.rb:137:in `command'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/app.rb:17:in `block in compile'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/kernel/reporting.rb:54:in `silence_stream'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/app.rb:16:in `compile'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli-rails.rb:66:in `block in each_app'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli-rails.rb:66:in `each'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli-rails.rb:66:in `each_app'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli-rails.rb:40:in `compile!'
remote:        /tmp/build_c29c20414fc576c1008f3b4d2b04e5f9/vendor/bundle/ruby/2.0.0/gems/ember-cli-rails-0.0.10/lib/ember-cli/helpers.rb:26:in `block (2 levels) in override_assets_precompile_task!'
```

**Comment by hone** [comment]
I'd be interested in making this awesome/supported.

**Comment by rwz** [comment]
@hone go for it! :+1:

**Comment by rondale-sc** [comment]
@hone that'd be awesome.  If you start and need a pair just let us know.  :))

**Comment by rwjblue** [comment]
@hone :heart:

**Comment by seanpdoyle** [comment]
I'll be working on fixing up the README and git history to explain whats going on, but I've successfully deployed https://github.com/seanpdoyle/ember-cli-rails-heroku-example

* sourced from https://github.com/seanpdoyle/ember-cli-rails-heroku-example
* depending on https://github.com/seanpdoyle/ember-cli-rails/tree/install-dependencies

Its a little messy, but it highlights what needs to change

**Comment by Samsinite** [comment]
Awesome work @seanpdoyle, anything I can help with to make this process even easier or streamlined?

**Comment by josemarluedke** [comment]
I was working on this as well. I have my app deployed to http://ember-cli-rails-heroku.herokuapp.com/ and it's code at https://github.com/josemarluedke/ember-cli-rails-heroku. 

I didn't have the time to write the process or open any issue yet. But you can check my commits to have an idea. Also I would love to work with you guys to improve the required changes as minimum as possible and make deploys to Heroku really smoothly.

**Comment by rondale-sc** [comment]
@josemarluedke Awesome!  I'll be sure to take a look.

**Comment by seanpdoyle** [comment]
I think the _cleanest_ solution would be a custom buildpack that takes all of this into account.

Having said that, I"m not sure of what it would take to write a single build pack that installs `node`, `npm`, `bower`, `ruby`, etc, without blindly copy-pasting the contents of the node and ruby buildpacks mentioned in the above examples' `.buildpacks` files.

**Comment by hone** [comment]
@seanpdoyle if possible, I'd actually like to avoid using a custom buildpack. My issue with it, is it's easy for them to get out of date and it's not going to be something that I'm going to look at and support in addition to the mainline Ruby one. Maybe there's enough stuff where there's a good case here.

**Comment by rwz** [comment]
@hone we've figured out Heroku deployments using official multibuildpack: https://github.com/rwz/ember-cli-rails/commit/c6cbe42eecf8fe9b9b9fadb6b7f646a66eed199f

It's super slow, but works ok for now.

**Comment by rwz** [comment]
Oh, and closed by https://github.com/rwz/ember-cli-rails/commit/c6cbe42eecf8fe9b9b9fadb6b7f646a66eed199f

**Comment by hone** [comment]
@rwz what's slow compared to a normal deploy?

**Comment by rwz** [comment]
@hone well, on EVERY deploy Heroku needs to run `npm install` and `bower install` completely from scratch for each EmberCLI app. And it usually takes forever. I'm thinking about caching node_modules and bower_components between deployments somehow, so Heroku can only resolve differences on each successive deploy, kind of like Ruby buildpack does with Bundler.

**Comment by hone** [comment]
@rwz the node buildpack caches npm_modules I thought? I'm pretty sure the bower stuff isn't cached by default in node. hmmm.

**Comment by rwz** [comment]
@hone it does it if it's root-level `node_modules`. We need caching for separate node apps within a root-app.

**Comment by hone** [comment]
ah right, that makes a ton of sense. maybe we need a custom buildpack here or should these be split out into separate apps?

**Comment by rwz** [comment]
@hone are you suggesting to split them up into separate apps with separate deployment process or just a virtual split, where it still deploys via a single app hook? I haven't look into buildpacks yet, so not sure what the options are.

**Comment by hone** [comment]
i was originally suggesting separate apps, so it'd take advantage of the buildpack's caching. What are you envisioning with the virtual split?

**Comment by rwz** [comment]
I dunno, I though there might be some Heroku black magic that you can enable to fire separate builds in separate subdirectories.

The whole point of this gem it to streamline EmberCLI development with conventional Rails and make deployments as Rails-like as possible. There're a bunch of other approaches that involve deploying EmberCLI frontend completely separately from API, but that gem doesn't do that.

**Comment by Samsinite** [comment]
Build packs are actually [pretty straight forward](https://devcenter.heroku.com/articles/buildpack-api#buildpack-api). They just consist of three following scripts that do *something*:
* `bin/detect` -- determine weather to apply this build pack to the app
* `bin/compile` -- performs transformation steps on app
* `bin/release` -- provides metadata back to the runtime

**Comment by Samsinite** [comment]
Couldn't the multi-buildpack's `. buildpacks` format just be modified to have a param that tells it to optionally fire the specified buildpack inside some BUILD_DIR sub-directory?

**Comment by hone** [comment]
it could, that seems pretty specific. It's totally possible to make this work though with caching.

**Comment by seanpdoyle** [comment]
@rwz @Samsinite @hone has anyone made any progress with caching? We're feeling the pain pretty badly and I'd love to figure this out.

Is there an approach to manually compose the ruby and node buildpacks, outside of copy-pasting their current `master` branches into a new buildpack?

**Comment by Samsinite** [comment]
There isn't an approach other than making a new buildpack or improving an
existing one. A slight modification to the multi-buildpack and its
`.buildpack` file would likely be the easiest solution. It could be
possible to get the changes merged upstream into that buildpack if the
owners are willing to support improving the .buildpack file in a backwards
compatible way. I'll try modifying it tonight to test.

-Sam

**Comment by seanpdoyle** [comment]
@hone @rwz @Samsinite I've hacked the `heroku-buildpack-nodejs` to work with a single, `app/frontend`

https://github.com/seanpdoyle/heroku-buildpack-nodejs/compare/ember-cli-rails

I've hard coded some caching for `app/frontend/{bower_components,node_modules}`, and it seems to work just fine.

There's still a MAJOR drawback: `rake assets:precompile` for a `rails new`'d app with `ember-cli-rails` takes ~3 minutes, EVERY deploy. I can't cache the assets, even with `config.assets.cache_store = :dalli_store` (http://blog.alexmaccaw.com/faster-deploys).

Any ideas?

**Comment by Samsinite** [comment]
Hmm... maybe it just takes the compilation that long? Maybe there is a way to do it locally?

**Comment by seanpdoyle** [comment]
@hone @rwz @Samsinite update:

I think it was taking forever because I hadn't disabled `config.assets.js_compressor = :uglifier`

I think the delay was due to the increased complexity of uglifiying the minified code that ember-cli was spitting out.

https://github.com/seanpdoyle/ember-cli-rails-heroku-example/compare/cache-node combined with https://github.com/seanpdoyle/ember-cli-rails/compare/nodejs-buildpack seems to have trimmed down the deploy times of the example project tremendously.

Unfortunately, the project that was the impetus for all of this is still prohibitively slow, even with the [custom buildpack][custom]

[custom]: https://github.com/seanpdoyle/heroku-buildpack-nodejs/compare/ember-cli-rails

**Comment by seanpdoyle** [comment]
@rwz @rondale-sc could we give https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker a shot?

I think it would solve all of our problems (right?):

* install node / bower / dependencies locally in the container
* compile production assets locally
* push the heroku compatible slug and re-deploy *"instantly"*

cc: @hone are my assumptions off?

**Comment by hone** [comment]
@seanpdoyle it would help for sure, but there's going to be a bunch of changes about to happen in the next month or so with that project, so I'd hold off.
