### ISSUE TITLE
Conditionally suppress Ember, Ember-Data and Handlebars from vendor.js

### ISSUE THREAD

**Issue by bradurani** [rwz/ember-cli-rails#44]
Similar to [this issue] (https://github.com/rwz/ember-cli-rails/issues/32), it would be nice to be able to prevent Ember, Ember-Data and Handlebars from being included in vendor.js if the ember-rails gem is present. This would be useful for sites that have more than one ember app. Currently, under this scenario, Ember, Ember-Data and Handlebars are downloaded once for each app.

Really, depending on the presence of the gems to detect jQuery and Ember doesn't cover all use cases. Many teams like to use Bower to include these in their Rails apps (I mean using Bower directly in Rails, not in Ember CLI). Since there's no way to detect that, maybe it would be useful to have additional options in the ember-cli-rails initializer that can manually suppress these imports?

I don't know enough about Ember CLI to know if it will build without Ember included though.

I'm willing to work on this if you think it's a good idea, but it will be a few weeks before I have the time. Thanks for the awesome gem!

**Comment by rwjblue** [comment]
ember-cli will absolutely build properly if Ember, Handlebars, and jQuery are all suppressed from the vendor output, but it would break when booting the app if those dependencies were not available (from other sources).

**Comment by rwjblue** [comment]
Perhaps this warrants some thought in the initializer (flags to enable/disable specific assets).  We can use good defaults (suppressing jQuery as we do already), but still make it simple to tweak...

**Comment by rwz** [comment]
I don't think going down that path will be too useful. Multiple apps are very likely to be well isolated from each other and even being developed and maintained by different people. I don't see too much value in trying to reduce duplication to that extent since it might cause more problems and be less transparent to users.

**Comment by rwz** [comment]
Maybe we could introduce this feature as an optional flag, so people can enable it explicitly if they know what they're doing.

**Comment by bradurani** [comment]
I may take a shot at it after I get back from CodeMash next week since we're experiencing the double download issue at work. I won't be offended if it doesn't make it into the gem though. Cheers!

**Comment by rondale-sc** [comment]
@bradurani +1 :))

**Comment by rwz** [comment]
Related: https://github.com/rwz/ember-cli-rails/issues/49

Crossposting my new **totally awesome** (!!!) idea about how we should deal with that:

```ruby
EmberCLI.configure do |config|
  config.app :frontend, exclude_vendor: %w[jquery ember-data some-other-script]
end
```

What do you guys think? //cc @rondale-sc @rwjblue

**Comment by rondale-sc** [comment]
@rwz This could be pulled into #55 maybe?

**Comment by bradurani** [comment]
Just came back to this project after a hiatus and found you've implemented my suggestion. Thanks a bunch!

**Comment by rondale-sc** [comment]
@braduran :+1:
