### ISSUE TITLE
Documentation: Where to create a new ember app in a Rails app

### ISSUE THREAD

**Issue by vovimayhem** [rwz/ember-cli-rails#46]
@rwz  Where do you suggest a newbie (in this case, me) can create an ember app (with ember-cli) for a Rails project?

That info would be useful for newbies, and could perfectly fit inside the project's README file.

As soon as I get an answer I can send you a PR with an updated README :)

**Comment by rwz** [comment]
Well, what do you mean "where"? Do you mean where in your Rails app the EmberCLI app should be? The suggested path would be `app/frontend` given your app is called "frontend".
