### ISSUE TITLE
vendor.js production asset's size is 0 bytes when using rake assets:precompile in production

### ISSUE THREAD

**Issue by venkatesh3007** [rwz/ember-cli-rails#48]

**Comment by rwz** [comment]
Well, I don't see why that's not ok. :)
Do you?

**Comment by venkatesh3007** [comment]
the application logs the error "define is not defined".. Am I missing something? It works well in my development machine but not in the production server.

**Comment by rwz** [comment]
Alright, that's a completely different issue.

**Comment by rwz** [comment]
Could you provide steps to reproduce the issue?

**Comment by venkatesh3007** [comment]
use the following:- 
ember-cli-rails version 0.0.15
ember-cli-rails-addon 0.0.7

then run RAILS_ENV=production rake assets:precompile

**Comment by rwz** [comment]
Nope, these steps don't work. Also, you're using an old version. Try a new one.

**Comment by venkatesh3007** [comment]
i will give it a try and get back

**Comment by rwz** [comment]
Closing this issue for now. Feel free to post your findings here so we can reopen. :)
