### ISSUE TITLE
Suppressing gems

### ISSUE THREAD

**Issue by MichaelVdheeren** [rwz/ember-cli-rails#49]
Please please make it possible to NOT suppress the use of jQuery-rails gem given the following scenario:

- Use ember-cli-rails
- Use ember-cli
- User rails-admin (which requires jQuery-rails)

So a boolean to prevent this would be perfect in the config files. As it is now we need to override the suppress function.

**Comment by rwz** [comment]
Ok, I understand that suppressing jquery by default without an override option was quite a bad idea. Here's a new one though:

```ruby
EmberCLI.configure do |config|
  config.app :frontend, exclude_vendor: %w[jquery ember-data some-other-script]
end
```

Basically, when you know what you're doing, you can provide an explicit list of things, you don't want EmberCLI to include into vendor.js bundle. How's that?

**Comment by MichaelVdheeren** [comment]
Looks good!
