### ISSUE TITLE
Export or sync rails models into ember cli apps

### ISSUE THREAD

**Issue by alexjp** [rwz/ember-cli-rails#57]
Hi,

Thanks for the awesome gem.

I have wondered, could there be a generator that could sync rails models into ember-cli apps, with the corresponding type ?

Something like having a user model in rails ( email, username, password) , with the generator, it would create the rails json serializer ( with email,username, password) and the ember cli model ( also with email, username password ).

Bonus points for the other way around, and specifiyng to more than one ember cli app and keeping them in sync.

What do you guys think ? I would make the "double mvc" overhead much easier to manage.

**Comment by rondale-sc** [comment]
@alexjp 

I suspect that an attempt to make this would result in some tricky assumptions that are probably not widely applicable.

That said there are already generators for active model serializers (widely used):  [here](https://github.com/rails-api/active_model_serializers#creating-a-serializer)

And generators for ember-cli models: [here](http://www.ember-cli.com/#blueprints)

Hopefully, those will get you pretty far. :)

*Side note*: I don't think there is a "double mvc" here.  A really great talk by @wycats described this very thing at gogaruco in 2013.  You should check it out, it was a real eye-opener for me.

["A Tale of Two MVC's"](https://www.youtube.com/watch?v=s1dhXamEAKQ)
