### ISSUE TITLE
Looking for assets in wrong path with re-written URI

### ISSUE THREAD

**Issue by sbsurf** [rwz/ember-cli-rails#61]
I have a rails app which is accessed like so:

    http://my.blah.com/joe_blow

where *joe_blow* might be any user portal name.

While the user sees the above url in the browser, the following Apache rewrite rule:

```javascript
  RewriteCond   %{HTTP_HOST}    ^my.
  RewriteCond   %{REQUEST_URI}  !^/[^\./]*\.[^/]*$
  RewriteRule   ^/([^/]*)/?(.*)  /$2?portal_slug=$1 [QSA,PT]
```
changes the request behind the scenes to:

    http://my.blah.com?portal_slug=joe_blow

After dynamically setting a base href in application.html.erb like so:

```javascript
<% portal_slug = request.portal_slug %>

<!DOCTYPE html>
<html>
<head>
  <base href=<%= "/#{portal_slug + '/' if portal_slug}" %>>
</head>
```

the rails app finds its assets with no issues. For example:

    /joe_blow/assets/application.js

However, this is not the case using using Ember-CLI and your gem. For whatever reason, it's trying to find the Ember-CLI app's assets under something like 
    
    /joe_blow/javascripts/frontend.js

(which I assume corresponds to *rails_app/app/assets/javascripts/frontend.js*)

instead of something like:

    /joe_blow/assets/frontend.js

(which would correspond to *rails_app/app/frontend/tmp/...*

If I pre-compile (build) the Ember-CLI assets, this issue still remains, as it always looks for the assets in that weird location.

Can you suggest an approach to getting your gem to work with my rails app?

**Comment by sbsurf** [comment]
I decided to go with a pure Ember-CLI app.

**Comment by rwz** [comment]
Good luck :+1:
