### ISSUE TITLE
Ember app in default path degrades perf of Rails

### ISSUE THREAD

**Issue by jesenko** [rwz/ember-cli-rails#66]
When Ember app is placed in Rails `/app` folder (i.e. default ember-cli-rails path), perf of Rails (rendering pages, serving assets, etc) degrades significantly due to large number of additional files (bower_components, node_modules) in Rails `autoload` path. 

Quick profiling led to the following method call:
`Rack/ActionDispatch::Reloader/call`
* < 1ms without EmberCLI app
* ~ 150ms with EmberCLI app

As a workaround, EmberCLI app can be just placed to any non-autoload path.

To avoid perf. problems I suggest the following:
* default app EmberCLI app path should be changed to something outside Rails `app` folder, e.g. `Rails.root.join('jsapp', <appname>)`
* Possible perf. problems when placing EmberCLI app in `app` folder should be mentioned in the readme.

I have only verified this issue on my local dev machine:
Rails 4.1.7
Ruby 2.2
OS X 10.9.5

**Comment by rwz** [comment]
Yep, we've noticed that as well. I wonder if there's a way to tell reloader to skip certain directories entirely. I've googled around and it seems like there're none.

I guess we'll have to change the default directory for ember apps in the next release.

**Comment by rondale-sc** [comment]
@rwz I think that is probably a good idea.  Kinda sucks for peeps with existent apps.  Do you think we should display a depcrecation warning for people with cli-apps in that dir?

**Comment by rwz** [comment]
Yeah, I'm thinking of the best way to handle this.

**Comment by AlexCppns** [comment]
Hello, I am running into the same problem, what would be a temporary fix? puts the emberjs app in a appjs folder? I also tested ember-rails but I feel I am gonna get stuck if I dont use ember-cli from the start.

**Comment by rwz** [comment]
@AlexCppns we've moved EmberCLI app into project root.
