### ISSUE TITLE
Can't precompile assets

### ISSUE THREAD

**Issue by nadavshatz** [rwz/ember-cli-rails#68]
Env:
Jruby 1.7.18
Rails 4.1.7
ember-cli-rials 0.1.1

When running
```bash
RAILS_ENV=production RACK_ENV=production bin/rake assets:precompile
```
I'm getting:
```
mkmf.rb can't find header files for ruby at /Users/nadav/.rbenv/versions/jruby-1.7.18/lib/native/include/ruby/ruby.h
```

**Comment by rwz** [comment]
Any additional info? Could you run rake with `--trace` flag maybe?

**Comment by nadavshatz** [comment]
```sh
/Users/nadav/.rbenv/versions/jruby-1.7.18/lib/ruby/shared/mkmf.rb:14: Use RbConfig instead of obsolete and deprecated Config.
mkmf.rb can't find header files for ruby at /Users/nadav/.rbenv/versions/jruby-1.7.18/lib/native/include/ruby/ruby.h
```

This is all i get when running with `--trace`

**Comment by rwz** [comment]
This doesn't look like EmberCLI Rails problem. That looks like a problem with your Ruby.

**Comment by nadavshatz** [comment]
Well, it works just fine without ember-cli-rails installed but ok

**Comment by nadavshatz** [comment]
Sorry - I don't think it's related anymore. just happened at the same time or something.

**Comment by nadavshatz** [comment]
Ok I've figured it out for anyone who might come across this. It didn't work until I took the ember-cli folder out of my /app folder.

Cheers

**Comment by rondale-sc** [comment]
@nadavshatz It is now recommended to keep your ember-cli app outside of the app folder (we haven't updated the readme yet) but you can see the relevant issue here https://github.com/rwz/ember-cli-rails/issues/66.

You're able to specify where your app is located by specifying the `path: /path/to/app/on/disk` in your initializer.
