### ISSUE TITLE
Conflicting chdir

### ISSUE THREAD

**Issue by tonywok** [rwz/ember-cli-rails#72]
I keep getting `warning: conflicting chdir during an other chdir block` when I run my tests. This is swallowing any test output. It's coming from `lib/ember-cli/app.rb:250`. 

Seems like a race condition? Seems `exec(cmd, method: :spawn)` is getting called multiple times. This is a little strange as to my knowledge my app server isn't making multiple threads and I only have one client app.

What application server are you all using?

Will report back once I've found the source.

**Comment by rwz** [comment]
Hm, that's interesting. `spawn` call should only happen once and only in dev environment. It shouldn't even happen in test. Are you using unicorn with multiple workers by any chance?

**Comment by tonywok** [comment]
@rwz Nope. Using capybara-webkit. I'll do some more debugging tomorrow.

**Comment by tonywok** [comment]
Seems to be related to some bizarre test setup code. Closing.

**Comment by rwz** [comment]
Let us know if you figure that out.
