### ISSUE TITLE
Can't compile Sass in production mode and can't debug it

### ISSUE THREAD

**Issue by glennfu** [rwz/ember-cli-rails#75]
I can run my app in development mode just fine, and I can run `rake assets:precompile` fine, but if I run `RAILS_ENV=production rake assets:precompile` I get this:

Sass::SyntaxError: Invalid CSS after "": expected selector or at-rule, was "{}"
  (in /Users/Glenn/Sites/ajam/ajam-mobile-middleware/tmp/ember-cli-576f8aa5-74f7-4d4c-9db7-56e96c0a41f8/assets/mm-ember/mm-ember.css.map)

"mm-ember" is the name of my ember-cli project folder. At this point, the file it references does not exist so I can't look into it. I don't know how to get more verbose output and I don't know how to disable source maps to see if that helps.

Any ideas for me?

**Comment by glennfu** [comment]
Another hint: `ember build --environment production` yields an mm-ember.css.map file with contents of "{}". I think this means that Sprockets/Sass via Rails is trying to actually process this as a .css file instead of recognizing that it's a .map file?

**Comment by glennfu** [comment]
OK nevermind on that hint. I updated my ember-cli-sass and got that disabled. Now `ember build --environment production` doesn't create a .css.map file. However when I run `RAILS_ENV=production RACK_ENV=production EMBER_ENV=production rake assets:precompile` I still get the same error about mm-ember.css.map.

**Comment by glennfu** [comment]
After updating ember-cli-sass to the master branch (latest release doesn't do) I can use one of its flags to disable .map generation and now I'm good to go.

I still think a better solution would be for ember-cli-rails to keep .map files out of /app/assets/stylesheets, but disabling it at least gets my app running and deploying to Heroku.

**Comment by rondale-sc** [comment]
@glennfu glad you were able to get this working.  I suspect trying to white/black list which files are symlinked by ember-cli-rails will be pretty hard to do in a way that won't break for others.  Going to close this for now, will reopen if I can think of anything

/cc @rwz
