### ISSUE TITLE
deployment using capistrano

### ISSUE THREAD

**Issue by rounders** [rwz/ember-cli-rails#81]
wondering if anyone has deployed an ember-cli-rails app using capistrano?

What should happen on the production server after deploy to ensure that the ember part of an ember-cli-rails app works?

I noticed that there are a couple of rake tasks (ember-cli:install_dependencies and ember-cli:compile). Should running both of those after deploy be sufficient ?

- thanks :-)

**Comment by jugglebird** [comment]
Francois.

Our application is deployed using capistrano. It's not significantly
different from a regular Rails deployment other than that we need to run an
npm install once the source is on the server and add the node_modules/bin
path to the environment.

--Chris

**Comment by rwz** [comment]
So, since version 0.1.5 everything should *just work*. Make sure you run `rake assets:precompile` on each deployment and that your server has Node/NPM installed.

**Comment by rounders** [comment]
@jugglebird , @rwz -- thanks for the info, that helps.  I went ahead and installed node on my server and then deployed using capistrano. It looks like it almost works. When capistrano precompiles the assets, I can see that most of the ember dependencies get installed, but then it fails with the following error message:

```shell
NoMethodError: undefined method `directory?' for nil:NilClass
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:307:in `block in each_entry'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:303:in `each'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:303:in `each_entry'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:322:in `block in each_file'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:321:in `each'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:321:in `each_file'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:335:in `each_logical_path'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:115:in `each'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:115:in `to_a'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:115:in `compile'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/data/mytestapp/shared/bundle/ruby/2.1.0/gems/ember-cli-rails-0.1.4/lib/ember-cli/helpers.rb:46:in `block (2 levels) in override_assets_precompile_task!'
```

Will report back if I can track it down.

**Comment by rwz** [comment]
You can start by trying to run `RAILS_ENV=production rake assets:precompile` locally.

**Comment by rounders** [comment]
@rwz - after some trial and error I found that rake assets:precompile works successfully on production if I manually run 'bower install' within the ember project folder first.

**Comment by rounders** [comment]
I followed the heroku instructions for adding a "postinstall" script and now bower install runs correctly when I do my capistrano deploy.

**Comment by rondale-sc** [comment]
@rounders Cool, glad it is working well.  Going to close this for now.  If you have any more concerns or questions just ping me and we can re-evaluate.

**Comment by hlogmans** [comment]
@rondale-sc I seem to run into the same problem. Exact error message, but this time it's originating from a missing bin folder in node_modules/ember-cli. I modified the postinstall to "postinstall": "bower install && npm install ember-cli@0.1.12". The version is needed otherwise 0.2.0-beta is installed. Because the errormessage is very generic and has lot of causes (wrong linking in ruby/capistrano config) that do not even point to ember, maybe some more advanced check if the Ember Build did succeed or not might be a very helpful hint to beginners like me.

**Comment by hlogmans** [comment]
pfffff ignore the part about the missing bin-folder... I'm also writing lost of c# code, and the bin folder is ignored by default in my bitbucket repositories :(.

**Comment by electricgraffitti** [comment]
Im also using the Capistrano deploy setup. When It hits the assets:precompile it fails saying 

sh: 1: prune: not found

the logs are not telling me too much, but Im assuming it has to do with Node somehow. 

Any advice?

**Comment by krnbatta** [comment]
@electricgraffitti Were you able to solve this?

**Comment by jindrichskupa** [comment]
@electricgraffitti @krnbatta 

Just install graphviz (on ubuntu or debian):

```
apt install graphviz
```
