### ISSUE TITLE
Errors and Exceptions should not be silently piped to an unreachable log file on Heroku

### ISSUE THREAD

**Issue by johnmcdowall** [rwz/ember-cli-rails#82]
In `app.rb` the output from executing the Ember-CLI build is silently piped to a log file:

https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L18

This is bad on Heroku, because it looks like the build succeeds and causes a downstream exception to be raised in Sprockets because the files it was told to expect don't exist because of the build failure. In general this is a bad thing™ to do. It is also a violation of the 12factor application principles with regard to logging: 

> It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout. During local development, the developer will view this stream in the foreground of their terminal to observe the app’s behaviour.

There are two ways I see to addressing this: 

0. Check for a specific EMBER_CLI_RAILS_VERBOSE environment variable that disables suppression of STDOUT.
0. Check for existence of BUILDPACK_URL environment variable to indicate we are running on Heroku and shouldn't suppress STDOUT. 

Happy to make PRs with the relevant changes if open to them.

**Comment by rondale-sc** [comment]
@johnmcdowall I think instead it'd be better to just remove the silence altogether.  `compile` is only run in production (on rake assets:precompile typically) and having a little extra noise there isn't a problem.  It seems as if this was a vestigial piece of code when we thought compile was going to be producing noise considerably more often.

**Comment by rondale-sc** [comment]
@johnmcdowall Started working on this.  Turns out we did this to avoid this gnarly output:

![](http://i.imgur.com/k5Ea19F.png)

We are likely going to make silencing this stream optional.  Will post more when I know.

**Comment by rwz** [comment]
![screen shot 2015-02-13 at 3 35 13 pm](https://cloud.githubusercontent.com/assets/129043/6194954/6160da00-b397-11e4-9d58-7cf7ecc97bc7.png)

So, it now doesn't silence the build output by default when
- it's not production (or Heroku build)
- there is an `EMBER_CLI_RAILS_VERBOSE` env variable

**Comment by rondale-sc** [comment]
@johnmcdowall Thanks :beers:

**Comment by johnmcdowall** [comment]
@rondale-sc Great work, thanks! :+1:
