### ISSUE TITLE
Static assets in an Ember project get asset hashed and made unreachable in production

### ISSUE THREAD

**Issue by johnmcdowall** [rwz/ember-cli-rails#83]
Create an ember project and include bootstrap. Create a test page with some glyphicons. 

Deploy to production. 

Glyphicons cannot be loaded, because Rails has gone ahead and asset hashed everything thus changing the filename that the Bootstrap CSS (that was compiled in your Ember app before it reaches rails) and now the filename used is incorrect. 

Perhaps more of an FYI?

**Comment by johnmcdowall** [comment]
Right, so this only affects older versions of Rails which don't automatically generate non-asset hashed versions.

**Comment by supairish** [comment]
@johnmcdowall  I thought it was the other way around.  Old versions of Rails compiled both a digest and non-digest version of assets.  Then they removed the non-digest version compilation.  So gems like this https://github.com/alexspeller/non-stupid-digest-assets appeared to "fix" that problem.  There is a super long rant thread about it here https://github.com/rails/sprockets-rails/issues/49   Did the most recent version of Rails revert this behaviour?

**Comment by johnmcdowall** [comment]
Acht, yes you’re right. Turns out we are running asset_sync which is doing this for us.
On February 11, 2015 at 6:49:45 PM, Chris Irish (notifications@github.com) wrote:

@johnmcdowall I thought it was the other way around. Old versions of Rails compiled both a digest and non-digest version of assets. Then they removed the non-digest version compilation. So gems like this https://github.com/alexspeller/non-stupid-digest-assets appeared to "fix" that problem. There is a super long rant thread about it here rails/sprockets-rails#49 Did the most recent version of Rails revert this behaviour?
