### ISSUE TITLE
Not working properly with Zeus

### ISSUE THREAD

**Issue by juliogarciag** [rwz/ember-cli-rails#87]
Hello mister mantainer :)

There is a problem with Zeus. Apparently, a signal 2 (https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L41) doesn't kill the ember child processes created while running within a server created by `zeus s` (`zeus server`).

This is a huge problem because when i press ctrl+c in a terminal running `zeus s` the rails process dies but not the child processes created. The screen seems to hangout and if i just close the terminal, the processes keep living and if i run `zeus s` again, more processes are created draining my battery and causing undesirable race conditions in the ember build process (i debugged one for a while before discovering that there was many embers running).

The proper solution would be to kill all the child process of the main ember process (to skip having some orphans). I already did this in my machine:

```ruby
exec("pkill -TERM -P #{pid}")
```

But i don't know if there is no other way to accomplish this. Do you think is a good solution to the problem? I know is a specific problem of people using Zeus so i'm asking what you think before making a PR.

PD: Sorry for my english.

**Comment by rwz** [comment]
So, when should this happen? Typically we're trying to kill the ember process when you quit the "main" rails process. Apparently Zeus keeps the process running in the background and `at_exit` hook doesn't fire. I'm not sure how we could detect server running under Zeus and start/kill processes appropriately in this scenario.

**Comment by juliogarciag** [comment]
Oh well.. the hook runs. If you set a debugger/binding.pry statement there the hook runs. The problem is that the kill uses a signal 2. I don't know exactly why but a signal 2 is something equivalent to a keyboard interrupt and within zeus, the rails process is not a top process but a child of the zeus process, and when the signal 2 happens (the `INT` signal) the spawned ember processes keeps running as orphans. The solution that worked is just to kill the process tree of the ember process (the ember process generates a child) instead of sending a signal 2. The code that should change is this method:

```ruby
def stop
  Process.kill "INT", pid if pid
  @pid = nil
end
```

to this:

```ruby
def stop
  exec("pkill -TERM -P #{pid}")
  @pid = nil
end
```

The problem is that i'm not sure of the disponibility of `pkill` in all unix-like environments or how this behaves under windows.

**Comment by rwz** [comment]
Why sending TERM instead of INT? How does that makes any difference?

**Comment by rwz** [comment]
We're sending this INT to the ember process, and it shouldn't matter whose child this ember process it. 

Also, could you try if sending HUP works?

**Comment by rondale-sc** [comment]
@juliogarciag ping
