### ISSUE TITLE
Little bug with latest ember-cli-version

### ISSUE THREAD

**Issue by djtal** [rwz/ember-cli-rails#88]
Hi,

First a big thanks for this project.

After installing this gem and following instructions I've found a little bug

ember-cli version just installed is **version: 0.2.0-beta.1**

And it seem you check for version [0.1.5](https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L6) so it break startup of the app with a explicit error message [here](https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L167)

Is it possible to bump the required version.

I actually added an initializer in my app which re-open [EmberCLI::App](https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb) to change the version but it seem a little bit ugly.

Tell me if you want more details or if I can help with that

**Comment by brian-meyers** [comment]
What was your fix? I'm experiencing this issue as well

**Comment by promisedlandt** [comment]
@brian-meyers I'm guessing in his initializer he does 

```ruby
module EmberCLI
  class App
    EMBER_CLI_VERSION = "~> 0.2"
  end
end
```

Very dirty of course, but seems to work.

**Comment by djtal** [comment]
Yes that's it. It ugly but it work for now.

**Comment by brian-meyers** [comment]
Dirty or not, this needs a fix! Thank you guys

**Comment by rwz** [comment]
Will definitely push a fix for that once 0.2 is stable.

**Comment by sphism** [comment]
Just ran into this same issue, awesome that you're already on to it, pasting the error below to help others find this page:

EmberCLI Rails require ember-cli NPM package version to be ~> 0.1.5 to work properly. From within your EmberCLI directory please update your package.json accordingly and run: $ npm install

**Comment by sphism** [comment]
Well that was a bugger to find how to fix.

To find where the gem is located you can use your terminal:

gem env

Then you get INSTALLATION DIRECTORY or GEM PATHS

I finally found the file, on my mac it's here:

/Library/Ruby/Gems/2.0.0/gems/ember-cli-rails-0.1.8/lib/ember-cli/app.rb

Change EMBER_CLI_VERSION = "~> 0.1.5"
to
EMBER_CLI_VERSION = "~> 0.2"

And ember now runs

**Comment by turboMaCk** [comment]
@sphism Changing gem's source is not good solution at all. Add this code in config/initializers/ember.rb is still better.

    module EmberCLI
      class App
        EMBER_CLI_VERSION = "~> 0.2"
      end
    end

    EmberCLI.configure do |c|
    # ...
    end

**Comment by sphism** [comment]
Thanks @turboMaCk that's exactly how my work mate fixed it, I'm new to all this.

It's odd that the code to compare version numbers fails to see that 0.2.0-beta.1 is greater than 0.1.5

**Comment by promisedlandt** [comment]
Absolutely as intended.  
Check [here](http://guides.rubygems.org/patterns/) under "Pessimistic version constraint".

**Comment by turboMaCk** [comment]
I think, that '~>' means 0.1.x so version 0.2.x is too high

**Comment by sphism** [comment]
ah, clever, i see...

**Comment by rondale-sc** [comment]
I believe that we should allow the usage of ember-cli 0.2.0 and 0.1.x during the transition period out of the box.  This would be to get good solid feedback on any breaking issues found by early adopters.  

I'm going to work with @rwz to make reopening the class unnecessary.

**Comment by rondale-sc** [comment]
Fixed [here](https://github.com/rwz/ember-cli-rails/commit/1bf8d2c5fb43e369b76819ffd5bd2bbcfb0fe14e)

version bump here: [`0.1.10`](https://github.com/rwz/ember-cli-rails/commit/87a0916eca44886262df0d1b6352413a45404f23).  

@rwz ready for tag and release :)

**Comment by stereobooster** [comment]
Bump. Current version of ember-cli is 1.13.1.

**Comment by Cortlandd** [comment]
@stereobooster  if you're having the error:
 (EmberCLI Rails require ember-cli NPM package version to be
["~> 0.1.5", "~> 0.2.0"] to...

Check your ember-cli-rails version. 0.3.4 includes 1.13.x. Had the same issue. Just update the gem
