### ISSUE TITLE
Don't correct all asset urls

### ISSUE THREAD

**Issue by MichaelVdheeren** [rwz/ember-cli-rails#96]
```test_html.gsub(%r{assets/}i, "assets/#{app_name}/")```
See: https://github.com/rwz/ember-cli-rails/blob/256314ae41223c66b76839a973a74fdbabc5a833/app/controllers/ember_tests_controller.rb#L9

Corrects all the assets links in the test index.html. However, sometimes you want a files from the rails asset pipeline using /assets/.... without the ember-cli app name

**Comment by rwz** [comment]
Is it safe to assume that ember assets are only called `vendor` and `<app-name>` at this point?

/cc @seanpdoyle @rondale-sc

**Comment by seanpdoyle** [comment]
@rondale-sc will have a better idea on how the Ember assets integrate with asset pipeline.

Mounting the tests routes was intended to remove the need to run a separate `ember s` or `ember test --serve` command to run JS only tests that exist in the EmberCLI project, not to serve as an end-to-end testing solution. 

If you're somehow depending on embedding Rails assets or views that depend on Rails assets into your Ember application, I would strongly recommend against that.

@MichaelVdheeren does your use of ember-cli-rails include embedding Rails assets into your Ember app, or are you depending on the `/assets` URL base existing on both sides?

Could you elaborate more on this particular use case?

**Comment by MichaelVdheeren** [comment]
We would like to use it for end-2-end testing (how can this otherwise be done using ember-cli-rails?). Hence we depend on the /assets url for both the ember-cli app and the additional assets like css being served from the rails asset pipeline

**Comment by seanpdoyle** [comment]
End-to-end testing should be done within Capybara feature tests with `js: true` (Rails including Ember), not in the QUnit test suite (Ember including Rails)

Correct me if I'm wrong: @rwz @rondale-sc

**Comment by rwz** [comment]
I approve of what @seanpdoyle said. We use cucumber for that.

**Comment by rondale-sc** [comment]
Yeah, end to end should be done with integration tools like capybara.  I think there is still a question mark over how we serve rails assets to ember tests running standalone. 

Until we answer how we want assets to be handled, using capybara is probably the only real way to run this type of test without keeping your assets silo'd inside the ember app that requires them. (which seems like a non solution atm)

**Comment by andruby** [comment]
Are you guys using Capybara for end-2-end testing? I'm a little sceptic to stray away from Ember's chosen default of Testem + Qunit. Testem easily supports proxying /api/ calls to a backend server. Capybara on the other hand has no knowledge of the Ember run loop and its asynchronous intricacies. I'm all ears if you have tips or insights on how to handle that.

[This post](https://medium.com/@thatandyrose/testing-ember-js-with-capybara-and-rspec-f793d7ddb49) describes using capybara with Ember as ".. what’s technically referred to as, **a hell ride.**". I'll give it a shot nonetheless :)

**Comment by rwz** [comment]
We've been using Cucumber/Capybara I personally have only good experience with it. Testing EmberCLI app is not any different then testing any other app.

Here's out `wait_for_ajax` implementation btw:

```ruby
def wait_for
  Timeout.timeout(Capybara.default_wait_time){ loop until yield }
end

def wait_for_javascript(expression)
  wait_for{ page.evaluate_script(expression) }
rescue Capybara::NotSupportedByDriverError
end

def wait_for_ajax
  wait_for_javascript "window.jQuery ? jQuery.active == 0 : true"
end
```

**Comment by rondale-sc** [comment]
@andruby Also, You can still write q-unit tests through ember-cli as long as the ember app you are testing has all the necessary styles (and other assets).   

You can run them from the command line with `ember-cli:test`.  Or server them as an engine with the instructions found [here](https://github.com/rwz/ember-cli-rails#ember-test-suite)

Or run them from your ember app with the standard `ember test --serve`

All that said, I agree with @rwz end2end test in cucumber have been pretty painless for me as well.
